ensure that AzBI module is runnable via cli
epiphany-platform/cli pull request #27
Opened 2021-01-04 16:58 UTC by mkyc

2021-01-11 14:18 UTC, erzetpe requested changes

2021-01-11 14:18 UTC, erzetpe commented on pkg/auth/ssh_test.go
> +func TestGenerateRsaKeyPair(t *testing.T) {
Why we need table driven tests for one test case?

2021-01-11 14:18 UTC, erzetpe commented on pkg/auth/ssh_test.go
> +func Test_generateRsaKeyPair(t *testing.T) {
Why we need table driven tests for one test case?

2021-01-11 14:18 UTC, erzetpe commented on pkg/processor/processor.go
> +func TemplateProcessor(c *configuration.Config, e *environment.Environment) func(s string) string {
Maybe we can use full variable names in functions?

2021-01-11 14:31 UTC, mkyc commented on pkg/auth/ssh_test.go
> +func TestGenerateRsaKeyPair(t *testing.T) {
Because that is readable convention in all tests. I have no idea how many cases there will be in future and having that simple table (because it's extremely simple) allows to be very flexible here.

2021-01-11 14:32 UTC, mkyc commented on pkg/auth/ssh_test.go
> +func Test_generateRsaKeyPair(t *testing.T) {
Because that is readable convention in all tests. I have no idea how many cases there will be in future and having that simple table (because it's extremely simple) allows to be very flexible here.

2021-01-11 14:42 UTC, mkyc commented on pkg/docker/docker.go
> +			if strings.HasSuffix(i.Name, rt) {
Updated.

2021-01-11 14:43 UTC, mkyc commented on pkg/processor/processor.go
> +func TemplateProcessor(c *configuration.Config, e *environment.Environment) func(s string) string {
Updated.

2021-01-12 12:21 UTC, seriva approved these changes

2021-01-12 12:21 UTC, seriva commented on pkg/auth/ssh_test.go
> +func TestGenerateRsaKeyPair(t *testing.T) {
For me its fine, I prefer the same convention for all tests instead of this one offs that are different.

2021-01-12 12:21 UTC, seriva commented on pkg/auth/ssh_test.go
> +func Test_generateRsaKeyPair(t *testing.T) {
For me its fine, I prefer the same convention for all tests instead of this one offs that are different.

2021-01-12 13:42 UTC, erzetpe approved these changes

2021-01-12 13:44 UTC, merged