Export/import environments
epiphany-platform/cli pull request #38
Opened 2021-02-15 11:51 UTC by atsikham

Draft

2021-02-16 12:26 UTC, mkyc reviewed
So in general I would think about moving import/export logic to another package. Current version is good enough but it lacks additional logic: 
 - cleaning of directory before export
 - validation that this is correct environment directory before import

For now it's ok but if we would like to add this logic command file is not good place for it.

2021-02-16 12:26 UTC, mkyc commented on cmd/environments-export.go
> +					debug("Found environment to export: %s", e.Uuid.String())
Please use direct `logger.Debug().Msgf(...)`.

2021-02-16 15:57 UTC, atsikham commented
> So in general I would think about moving import/export logic to another package. Current version is good enough but it lacks additional logic:
> 
> * cleaning of directory before export
> * validation that this is correct environment directory before import
> 
> For now it's ok but if we would like to add this logic command file is not good place for it.

Could you take a look again?

2021-02-17 09:25 UTC, mkyc reviewed
Just some thoughts on current code stage

2021-02-17 09:25 UTC, mkyc commented on cmd/environments-export.go
> +		if !isCurrentEnvUsed {
isn't it just else to `if` from line 44?

2021-02-17 09:25 UTC, mkyc commented on cmd/environments-import.go
> +			srcFile, _ = promptui.PromptForString("File to export environment from")
```suggestion
			srcFile, _ = promptui.PromptForString("File to import environment from")
```

2021-02-17 09:25 UTC, mkyc commented on cmd/environments-import.go
> +			// Check if environment with such id is already in place
```suggestion
			// Check if provided source file exists
```

2021-02-17 09:25 UTC, mkyc commented on cmd/environments-import.go
> +			if _, err := os.Stat(srcFile); err != nil {
I think this `if` should be outside of first one. You want to check existence of file no matter how path was provided.

2021-02-17 09:25 UTC, mkyc commented on cmd/environments-import.go
> +		err = config.SetUsedEnvironment(*envID)
I think you can add this `IsValid` method to be called inside `SetUsedEnvironment` if that is possible.

2021-02-17 09:25 UTC, mkyc commented on pkg/environment/environment.go
> +	err := archiver.Archive([]string{envPath}, path.Join(dstDir, envID)+".zip")
```suggestion
	err := archiver.Archive([]string{envPath}, path.Join(dstDir, envID+".zip"))
```
that feels more natural in my opinion

2021-02-17 09:25 UTC, mkyc commented on pkg/environment/environment.go
> +
I think that somewhere here we should copy directory to temporary directory and then perform some `cleanDirectoryBeforeExport()` (this is dumb name) and package this cleaned directory.

2021-02-17 09:25 UTC, mkyc commented on pkg/environment/environment.go
> +	envConfigDir := path.Join(util.GetHomeDirectory(), util.DefaultConfigurationDirectory, util.DefaultEnvironmentsSubdirectory)
Isn't there already variable `util.UsedEnvironmentsSubdirectory` ... I believe there is.

2021-02-22 08:27 UTC, atsikham commented on pkg/environment/environment.go
> +	envConfigDir := path.Join(util.GetHomeDirectory(), util.DefaultConfigurationDirectory, util.DefaultEnvironmentsSubdirectory)
Yes, checked and there is `util.UsedEnvironmentDirectory`

2021-02-23 17:03 UTC, mkyc requested changes
Some little comments. I didn't read environment_test.go but I'll try to check it tomorrow in IDE directly form your branch.

2021-02-24 11:54 UTC, mkyc requested changes
Answering your question in description of this PR, my opinion is that Import/Export is tested well enough in not to test it fully in `cmd/cmd_test.go`. I would test just invocation of method and incorrect invocation and check that outputs are as expected. So for example I would test `e environments export --id incorrect --destination /incorrect` and couple of similar, just to check error messages in communication with user.

2021-02-24 11:54 UTC, mkyc commented on cmd/cmd_test.go
> +		// TODO: uncomment when environments removal is implemented
why this is commented?

2021-02-24 11:54 UTC, mkyc commented on pkg/environment/environment_test.go
> +	}
isn't is better to add this to `setup()` method?

2021-02-24 11:54 UTC, mkyc commented on pkg/environment/environment_test.go
> +	os.RemoveAll(path.Join(util.UsedEnvironmentDirectory, importEnvInvalidFirst.Uuid.String()))
this whole code looks like it should go to separate function named i.e.: `prepareImportTestPrereqs()` or something like this.

2021-02-24 11:54 UTC, mkyc commented on pkg/environment/environment_test.go
> +	err = importEnvValidFirst.Export(util.UsedConfigurationDirectory)
This is optional suggestion, but I wouldn't do this here. I would run exactly code using packaging depandency here, and I would not use our method here. Reason is that if `Export` method will get broken you might have `Import` related test corrupted.

2021-02-24 13:28 UTC, atsikham commented on cmd/cmd_test.go
> +		// TODO: uncomment when environments removal is implemented
It creates a new environment each tests execution and as a result you have it mixed up with yours environments.

2021-02-25 10:17 UTC, atsikham commented on cmd/environments-export.go
> +			envID = config.CurrentEnvironment
great catch

2021-02-25 10:24 UTC, atsikham commented on cmd/environments-import.go
> +		}
`Import()` returns a pointer, should that be changed?

2021-02-25 10:43 UTC, mkyc commented on cmd/environments-import.go
> +		}
I just meant to switch order maybe like following code: 

```golang
  		// Switch to the imported environment
 		config, err := configuration.GetConfig()
 		if err != nil {
 			logger.Fatal().Err(err).Msg("Get config failed")
 		}
		// Import environment
 		envID, err := environment.Import(srcFile)
 		if err != nil {
 			logger.Fatal().Err(err).Msg("Unable to import environment from specified file")
 		}
```

2021-02-25 10:45 UTC, atsikham commented on cmd/environments-import.go
> +		}
this was a comment in a wrong place, sorry.

2021-02-25 13:16 UTC, atsikham commented on pkg/configuration/configuration_test.go
> +			ioutil.WriteFile(path.Join(envDirSwitch, util.DefaultEnvironmentConfigFileName), []byte(fmt.Sprintf(envConfigTemplate, "env2", envIDSwitch)), 0644)
Created a separate `prepareSetUsedEnvironmentPrereqs()` function as it's required only for this particular test.

2021-03-01 11:22 UTC, mkyc approved these changes
LGTM

2021-03-01 13:32 UTC, seriva approved these changes

2021-03-01 14:08 UTC, mkyc approved these changes

2021-03-01 14:09 UTC, merged

2021-03-15 15:43 UTC, przemyslavic commented
/azp run